Nicer error message/behaviour if no configuration.
Rather than `Error:  undefined method `[]' for nil:NilClass` or
`Error:  undefined method `each' for nil:NilClass`, print out a
message saying the config is missing, or allow through an empty
config.